<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.3 setup script
 * Date: Mon, 18 Jul 2016 21:25:36 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'shamW0W!';
$cfg['Servers'][$i]['AllowRoot'] = 'on';
$cfg['Servers'][$i]['MaxTableUiprefs'] = '100';
$cfg['Servers'][$i]['tracking_add_drop_view'] = 'on';
$cfg['Servers'][$i]['tracking_add_drop_table'] = 'on';
$cfg['Servers'][$i]['tracking_add_drop_database'] = 'on';

/* End of servers configuration */

$cfg['blowfish_secret'] = '578d2c69451de1.38544975';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = '1';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
